### ISSUE TITLE
phone validation to support other country codes.

### ISSUE THREAD

**Issue by bettdalpha** [jebright/flutter_validate#1]
Your plugin only supports US code validation. Is there a way you can extend it to support other countries or should I make a pull req?
![Screenshot_20190606-143437](https://user-images.githubusercontent.com/28408089/59030040-7c9ab200-8868-11e9-9917-16fff7d13fa1.png)

**Comment by bettdalpha** [comment]
I used the regex [0-9]{0,14}$ to validate that.

**Comment by jebright** [comment]
Glad to hear that worked out for you.  I designed the validator to be open enough to do just that.  But I will be looking into better internationalization in the future.
