### ISSUE TITLE
Published version seems to be behind

### ISSUE THREAD

**Issue by rhalff** [jebright/flutter_validate#2]
I'm trying to use this package but although the published version is 1.0.0 the code is older than within this repository which has a version of 0.0.1

 e.g. the published version does not have a `RuleEngine`.

**Comment by jebright** [comment]
Apologies for the issue.  The develop branch had changes that were never merged to master.  Everything is now up to date in master.  I will be publishing a 1.0.1 version to the package later today.  Will close this when that is done.

**Comment by jebright** [comment]
published version now is up to date with latest code base.  https://pub.dev/packages/flutter_validate/versions/1.0.1

**Comment by rhalff** [comment]
Thanks for the merge and update!

**Comment by rhalff** [comment]
Seems my pull request was based on a different version, the `_delimiter` is not being used and the old comment re-appeared.  https://github.com/jebright/flutter_validate/commit/ce6d4b168a4458ab60c32b4559867971c211a953

Is it correct that the published version doesn't make use of a `RuleEngine`?

**Comment by jebright** [comment]
Correct, the published version does not make use of a RuleEngine any longer.  It was refactored out during initial development and no longer needed.  Check out my blog post on this validation library and do feel free to ping me back here with any further questions.
https://codingwithjoe.com/a-fluent-validation-library-for-dart-and-flutter/

**Comment by rhalff** [comment]
The usage of delimiter got lost in the merge, the pull request fixes that.

**Comment by jebright** [comment]
You are of course correct.  During my merge of your pull request I ran into merge conflicts and did not get the merge correct.  Thank you for submitting another pull request - which I merged.
